### ISSUE TITLE
libcurl integration

### ISSUE THREAD

**Issue by arcanis** [dermesser/uvco#1]
C++ coroutines are difficult to use, it's nice to find an up-to-date project putting them and libuv together!

Did you consider integrating libcurl within your framework, possibly starting from the [example](https://curl.se/libcurl/c/multi-uv.html) they provide? This way you'd have a battle-tested client that would natively support all of http 1, 2, and ssl.

**Comment by dermesser** [comment]
Hi @arcanis, thank you very much for your interest in uvco! As I'm currently working on making the code more robust, a similar idea already came up (I wondered about TLS encryption, specifically). Thank you for the pointer towards libcurl, I will definitely check to see how this can fit.

**Comment by dermesser** [comment]
I've implemented a barebones, download-only libcurl client ready for use: https://borgac.net/~lbo/doc/uvco/classuvco_1_1Curl.html

Here's a few examples of how to use it: https://github.com/dermesser/uvco/blob/master/test/curl_test.cc
